//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuitappRest.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountDataEntry
    {
        public int AccountID { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<int> FYearID { get; set; }
        public Nullable<decimal> DebitAmount { get; set; }
        public Nullable<decimal> CreditAmount { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
        public Nullable<int> DebitAccount { get; set; }
        public Nullable<int> CreditAccount { get; set; }
        public string DebitAccountName { get; set; }
        public string CreditAccountName { get; set; }
        public string CompoundNarration { get; set; }
        public Nullable<int> Cancel { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string VoucherType { get; set; }
        public string Narration { get; set; }
        public Nullable<int> IsAccountable { get; set; }
        public Nullable<int> BankID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateAndTime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateAndTime { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDateAndTime { get; set; }
        public Nullable<int> BillID { get; set; }
        public Nullable<int> BillAmount { get; set; }
        public Nullable<int> PurchaseNo { get; set; }
        public Nullable<int> PurchaseReturnNo { get; set; }
        public Nullable<int> BillNo { get; set; }
        public Nullable<int> BillReturnNo { get; set; }
    }
}
