//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuitappRest.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcGroupMaster
    {
        public int GSlNo { get; set; }
        public string GName { get; set; }
        public int GUnder { get; set; }
        public bool BsPl { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
        public string Type { get; set; }
        public Nullable<int> TBSlNo { get; set; }
        public int Isdeleted { get; set; }
        public Nullable<int> CompanyId { get; set; }
    }
}
