//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuitappRest.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public int Slno { get; set; }
        public int HeadNo { get; set; }
        public string BankName { get; set; }
        public int GUnder { get; set; }
        public string Place { get; set; }
        public string Branch { get; set; }
        public string PhoneNo1 { get; set; }
        public string AccNo { get; set; }
        public Nullable<System.DateTime> BDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public int Isdeleted { get; set; }
    }
}
