//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuitappRest.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillPayment
    {
        public int SlNo { get; set; }
        public Nullable<int> BillNo { get; set; }
        public string BillType { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<int> HSlNO { get; set; }
    }
}
