//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuitappRest.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingEdittedDiscount
    {
        public int BillID { get; set; }
        public int BillNo { get; set; }
        public System.DateTime EnteringDate { get; set; }
        public System.DateTime BillDate { get; set; }
        public int BillMode { get; set; }
        public string CustomerName { get; set; }
        public int FYearID { get; set; }
        public decimal BillAmount { get; set; }
        public int SupplyMode { get; set; }
        public int IsAccountable { get; set; }
        public int LocationID { get; set; }
        public string TinNo { get; set; }
        public string Bank { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public decimal PendingAmount { get; set; }
        public decimal PaidAmount { get; set; }
        public int CreditSale { get; set; }
        public int ContainerCount { get; set; }
        public decimal ContainerAmount { get; set; }
        public string WholeSaleRetail { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDateAndTime { get; set; }
        public int ModifiedBy { get; set; }
        public Nullable<System.DateTime> MofifiedDateAndTime { get; set; }
        public int DeletedBy { get; set; }
        public int IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDateAndTime { get; set; }
        public int CompanyID { get; set; }
        public int RetailBillNo { get; set; }
    }
}
