//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuitappRest.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string GstNo { get; set; }
        public string Address { get; set; }
        public int Mobileno { get; set; }
        public Nullable<int> Phoneno { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public int Pincode { get; set; }
    }
}
