//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuitappRest.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class form
    {
        public int frmId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Name { get; set; }
        public string FrmName { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime Created_Date_And_Time { get; set; }
        public int ModifiedBy { get; set; }
        public Nullable<System.DateTime> Modified_DateAndTime { get; set; }
        public int Deleted_BY { get; set; }
        public int IsDeleted { get; set; }
        public Nullable<System.DateTime> Deleted_Date_And_Time { get; set; }
    }
}
