//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuitappRest.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralSetting
    {
        public int LoginID { get; set; }
        public int DefaultCashAccountGroupID { get; set; }
        public int DefaultBankAccountGroupID { get; set; }
        public int DefaultSupplierGroupID { get; set; }
        public int DefaultCustomerGroupID { get; set; }
        public string DefaultComapanyNameForPrint { get; set; }
        public string DatabaseName { get; set; }
        public string ServerName { get; set; }
        public int DefaultSalesAccountGroupID { get; set; }
        public int FYearID { get; set; }
        public string RatePercentage { get; set; }
        public int Companyid { get; set; }
        public int DefaultPurchaseAccountGroupID { get; set; }
        public int UnloadingAccountID { get; set; }
        public int FreifgtAccountID { get; set; }
        public int RoundOff { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
    }
}
