//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuitappRest.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemStockTemp
    {
        public int ItemID { get; set; }
        public string ItemCode { get; set; }
        public int CategoryID { get; set; }
        public string BatchNo { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public int CurrentQuantity { get; set; }
        public int LocationID { get; set; }
        public int CompanyID { get; set; }
    }
}
