//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuitappRest.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCategory
    {
        public int CategoryID { get; set; }
        public string CatgoryName { get; set; }
        public string CategoryCode { get; set; }
        public int CategoryType { get; set; }
        public int CategoryParent { get; set; }
        public int TaxID { get; set; }
        public string TaxName { get; set; }
        public int level { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDateAndTime { get; set; }
        public int ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateAndTime { get; set; }
        public int DeletedbY { get; set; }
        public int IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDateAndTime { get; set; }
        public string SCategory { get; set; }
    }
}
