//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuitappRest.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class KOT
    {
        public int KOID { get; set; }
        public string TokenNo { get; set; }
        public Nullable<int> InvoiceNo { get; set; }
        public Nullable<decimal> NetAmt { get; set; }
        public string SuitApp_Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<int> IsReady { get; set; }
        public Nullable<int> IsRevoke { get; set; }
        public Nullable<int> PaymentMode { get; set; }
        public string Series { get; set; }
    }
}
