//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuitappRest.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class KOTDetail
    {
        public int KDID { get; set; }
        public int KOID { get; set; }
        public int ItemID { get; set; }
        public int Qty { get; set; }
        public decimal NetAmt { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> GrossValue { get; set; }
        public string TaxRate { get; set; }
        public Nullable<decimal> TaxAmt { get; set; }
        public string CGSTRate { get; set; }
        public Nullable<decimal> CGSTAmt { get; set; }
        public string SGSTRate { get; set; }
        public Nullable<decimal> SGSTAmt { get; set; }
        public string SuitAppId { get; set; }
    }
}
