//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuitappRest.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class openingstock
    {
        public int OpeningId { get; set; }
        public int locationId { get; set; }
        public System.DateTime openingDate { get; set; }
        public decimal TotalpurchaseAmount { get; set; }
        public int IsDeleted { get; set; }
        public int companyId { get; set; }
        public int OpeningNo { get; set; }
    }
}
