//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuitappRest.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrder
    {
        public int SOID { get; set; }
        public System.DateTime Date { get; set; }
        public string OrderNo { get; set; }
        public int CustomerID { get; set; }
        public int UserID { get; set; }
        public int CompanyID { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> AdvanceAmo { get; set; }
        public decimal TotAmo { get; set; }
        public int OrderStatus { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int DeletedBy { get; set; }
        public System.DateTime DeletedDate { get; set; }
        public int IsDeletedBy { get; set; }
        public string SuitApps_id { get; set; }
        public string Customer_SuitAppId { get; set; }
    }
}
