//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuitappRest.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderDetail
    {
        public int SODID { get; set; }
        public int SOID { get; set; }
        public int ItemID { get; set; }
        public double Qty { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public string SuitApps_id { get; set; }
        public Nullable<double> FreeQty { get; set; }
        public Nullable<decimal> Rate { get; set; }
    }
}
