//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuitappRest.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOrderDetailsTemp
    {
        public int SODID { get; set; }
        public Nullable<int> SOID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
    }
}
