//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuitappRest.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public int StateID { get; set; }
        public string StateName { get; set; }
        public string StateCode { get; set; }
        public int StateType { get; set; }
        public int StateParent { get; set; }
        public int level { get; set; }
        public int createdBy { get; set; }
        public System.DateTime CreatedDateAndTime { get; set; }
        public int ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateAndTime { get; set; }
        public int DeletedBy { get; set; }
        public int IsDeleted { get; set; }
        public System.DateTime DeletedDateAndTime { get; set; }
        public string Scategory { get; set; }
    }
}
