//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuitappRest.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockAdjestmentDetaile
    {
        public int BillID { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> SubCategory { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<decimal> CurrentStock { get; set; }
        public Nullable<decimal> IssueReceipt { get; set; }
        public Nullable<decimal> NetQuantity { get; set; }
        public string Narration { get; set; }
        public Nullable<int> BatchId { get; set; }
    }
}
