//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuitappRest.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockRegisterFoeEstimate
    {
        public int EstmateID { get; set; }
        public int ItemID { get; set; }
        public string ItemCode { get; set; }
        public int ItemCategory { get; set; }
        public string ItemName { get; set; }
        public int UnitID { get; set; }
        public string BatchNo { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public decimal CurrentQuantity { get; set; }
        public int PurchaseMode { get; set; }
        public int LocationID { get; set; }
        public decimal Price { get; set; }
        public decimal Total { get; set; }
        public string Location { get; set; }
        public int CompanyID { get; set; }
        public decimal BookingQuantity { get; set; }
        public int EstimateNO { get; set; }
        public decimal BilledQuantity_Estimate { get; set; }
        public int BillNo { get; set; }
        public int EstimateNoRetail { get; set; }
        public string Customer { get; set; }
    }
}
