//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuitappRest.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockAdjestment
    {
        public int BillId { get; set; }
        public int RefSlno { get; set; }
        public Nullable<System.DateTime> ADDate { get; set; }
        public Nullable<int> GodownId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    }
}
