//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuitappRest.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLoginHistory
    {
        public int ID { get; set; }
        public int EmployeeCode { get; set; }
        public string EmployeeName { get; set; }
        public string LoginUserName { get; set; }
        public System.DateTime DateIN { get; set; }
        public System.DateTime TimeIN { get; set; }
        public System.DateTime DateOUT { get; set; }
        public System.DateTime TimeOUT { get; set; }
        public string IPAddress { get; set; }
    }
}
